# Generated by Django 5.2.5 on 2025-09-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giverollApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='prize',
            field=models.ManyToManyField(to='giverollApp.prize'),
        ),
    ]
