# Generated by Django 5.2.5 on 2025-09-05 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giverollApp', '0002_alter_draw_prize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Brand_name',
            new_name='brand_name',
        ),
    ]
