# Generated by Django 5.2.5 on 2025-09-05 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giverollApp', '0003_rename_brand_name_user_brand_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draw',
            name='prize',
        ),
        migrations.AddField(
            model_name='prize',
            name='draw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='giverollApp.draw'),
        ),
    ]
