# Generated by Django 5.2.5 on 2025-09-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giverollApp', '0004_remove_draw_prize_prize_draw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participants',
            old_name='platorm',
            new_name='platorm_s',
        ),
        migrations.AlterUniqueTogether(
            name='participants',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='winners',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='winners',
            name='bank_account_name',
        ),
        migrations.RemoveField(
            model_name='winners',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='winners',
            name='confirmation_code',
        ),
        migrations.RemoveField(
            model_name='winners',
            name='pickup_address',
        ),
        migrations.AddField(
            model_name='participants',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participants',
            name='platorm_f',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='winners',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='winners',
            name='social_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='winners',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='winners',
            name='street_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='participants',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='participants',
            name='social_handle',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='winners',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='participants',
            constraint=models.UniqueConstraint(fields=('draw', 'email'), name='unique_draw_email'),
        ),
        migrations.AddConstraint(
            model_name='participants',
            constraint=models.UniqueConstraint(fields=('draw', 'ip_address'), name='unique_draw_ip'),
        ),
        migrations.AddConstraint(
            model_name='participants',
            constraint=models.UniqueConstraint(fields=('draw', 'social_handle'), name='unique_draw_social_handle'),
        ),
    ]
