# Generated by Django 5.2.5 on 2025-09-06 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giverollApp', '0005_rename_platorm_participants_platorm_s_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participants',
            old_name='platorm_f',
            new_name='platform_f',
        ),
        migrations.RenameField(
            model_name='participants',
            old_name='platorm_s',
            new_name='platform_s',
        ),
    ]
